global:
  scrape_interval: 5s
  evaluation_interval: 60s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
  
rule_files:
  - '/etc/prometheus/recording_rules.yml'